# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b2b14eda91b1de6231a4d179819ab6561c23f8788a47e625e4030df6bb84425a78058dc748c3ef3c9d06fe1e25a30ae723592559b97a83bc2e7cead00b2220

test:
  secret_key_base: ccfa5e73c447741081623a1a6a35654745f85901dfc9f5735ab8cd3efc42de3d740d6508272e473a2355aa5f13b61bbee900cbb6b0e75384e2bff77da1d9fa49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
